/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.nipe.liferay.service.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Training service. Represents a row in the &quot;Sample_Training&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>at.nipe.liferay.service.builder.model.impl.TrainingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>at.nipe.liferay.service.builder.model.impl.TrainingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Training
 * @generated
 */
@ProviderType
public interface TrainingModel
	extends BaseModel<Training>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a training model instance should use the {@link Training} interface instead.
	 */

	/**
	 * Returns the primary key of this training.
	 *
	 * @return the primary key of this training
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this training.
	 *
	 * @param primaryKey the primary key of this training
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this training.
	 *
	 * @return the uuid of this training
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this training.
	 *
	 * @param uuid the uuid of this training
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the training ID of this training.
	 *
	 * @return the training ID of this training
	 */
	public long getTrainingId();

	/**
	 * Sets the training ID of this training.
	 *
	 * @param trainingId the training ID of this training
	 */
	public void setTrainingId(long trainingId);

	/**
	 * Returns the group ID of this training.
	 *
	 * @return the group ID of this training
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this training.
	 *
	 * @param groupId the group ID of this training
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this training.
	 *
	 * @return the company ID of this training
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this training.
	 *
	 * @param companyId the company ID of this training
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this training.
	 *
	 * @return the user ID of this training
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this training.
	 *
	 * @param userId the user ID of this training
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this training.
	 *
	 * @return the user uuid of this training
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this training.
	 *
	 * @param userUuid the user uuid of this training
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this training.
	 *
	 * @return the user name of this training
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this training.
	 *
	 * @param userName the user name of this training
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this training.
	 *
	 * @return the create date of this training
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this training.
	 *
	 * @param createDate the create date of this training
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this training.
	 *
	 * @return the modified date of this training
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this training.
	 *
	 * @param modifiedDate the modified date of this training
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the trainer of this training.
	 *
	 * @return the trainer of this training
	 */
	@AutoEscape
	public String getTrainer();

	/**
	 * Sets the trainer of this training.
	 *
	 * @param trainer the trainer of this training
	 */
	public void setTrainer(String trainer);

	/**
	 * Returns the name of this training.
	 *
	 * @return the name of this training
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this training.
	 *
	 * @param name the name of this training
	 */
	public void setName(String name);

	/**
	 * Returns the date of this training.
	 *
	 * @return the date of this training
	 */
	public Date getDate();

	/**
	 * Sets the date of this training.
	 *
	 * @param date the date of this training
	 */
	public void setDate(Date date);

	/**
	 * Returns the hours of this training.
	 *
	 * @return the hours of this training
	 */
	public Double getHours();

	/**
	 * Sets the hours of this training.
	 *
	 * @param hours the hours of this training
	 */
	public void setHours(Double hours);

}