/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package at.nipe.liferay.service.builder.model.impl;

import at.nipe.liferay.service.builder.model.Training;
import at.nipe.liferay.service.builder.model.TrainingModel;
import at.nipe.liferay.service.builder.model.TrainingSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Training service. Represents a row in the &quot;Sample_Training&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TrainingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrainingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TrainingModelImpl
	extends BaseModelImpl<Training> implements TrainingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a training model instance should use the <code>Training</code> interface instead.
	 */
	public static final String TABLE_NAME = "Sample_Training";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"trainingId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"trainer", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"date_", Types.TIMESTAMP}, {"hours", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trainingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("trainer", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("date_", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hours", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Sample_Training (uuid_ VARCHAR(75) null,trainingId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,trainer VARCHAR(75) null,name VARCHAR(75) null,date_ DATE null,hours DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table Sample_Training";

	public static final String ORDER_BY_JPQL =
		" ORDER BY training.date ASC, training.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Sample_Training.date_ ASC, Sample_Training.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long NAME_COLUMN_BITMASK = 4L;

	public static final long TRAINER_COLUMN_BITMASK = 8L;

	public static final long UUID_COLUMN_BITMASK = 16L;

	public static final long DATE_COLUMN_BITMASK = 32L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Training toModel(TrainingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Training model = new TrainingImpl();

		model.setUuid(soapModel.getUuid());
		model.setTrainingId(soapModel.getTrainingId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTrainer(soapModel.getTrainer());
		model.setName(soapModel.getName());
		model.setDate(soapModel.getDate());
		model.setHours(soapModel.getHours());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Training> toModels(TrainingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Training> models = new ArrayList<Training>(soapModels.length);

		for (TrainingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TrainingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _trainingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTrainingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _trainingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Training.class;
	}

	@Override
	public String getModelClassName() {
		return Training.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Training, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Training, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Training, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Training)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Training, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Training, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Training)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Training, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Training, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Training>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Training.class.getClassLoader(), Training.class,
			ModelWrapper.class);

		try {
			Constructor<Training> constructor =
				(Constructor<Training>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Training, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Training, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Training, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Training, Object>>();
		Map<String, BiConsumer<Training, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Training, ?>>();

		attributeGetterFunctions.put("uuid", Training::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Training, String>)Training::setUuid);
		attributeGetterFunctions.put("trainingId", Training::getTrainingId);
		attributeSetterBiConsumers.put(
			"trainingId", (BiConsumer<Training, Long>)Training::setTrainingId);
		attributeGetterFunctions.put("groupId", Training::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Training, Long>)Training::setGroupId);
		attributeGetterFunctions.put("companyId", Training::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Training, Long>)Training::setCompanyId);
		attributeGetterFunctions.put("userId", Training::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Training, Long>)Training::setUserId);
		attributeGetterFunctions.put("userName", Training::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Training, String>)Training::setUserName);
		attributeGetterFunctions.put("createDate", Training::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Training, Date>)Training::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Training::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Training, Date>)Training::setModifiedDate);
		attributeGetterFunctions.put("trainer", Training::getTrainer);
		attributeSetterBiConsumers.put(
			"trainer", (BiConsumer<Training, String>)Training::setTrainer);
		attributeGetterFunctions.put("name", Training::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Training, String>)Training::setName);
		attributeGetterFunctions.put("date", Training::getDate);
		attributeSetterBiConsumers.put(
			"date", (BiConsumer<Training, Date>)Training::setDate);
		attributeGetterFunctions.put("hours", Training::getHours);
		attributeSetterBiConsumers.put(
			"hours", (BiConsumer<Training, Double>)Training::setHours);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTrainingId() {
		return _trainingId;
	}

	@Override
	public void setTrainingId(long trainingId) {
		_trainingId = trainingId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTrainer() {
		if (_trainer == null) {
			return "";
		}
		else {
			return _trainer;
		}
	}

	@Override
	public void setTrainer(String trainer) {
		_columnBitmask |= TRAINER_COLUMN_BITMASK;

		if (_originalTrainer == null) {
			_originalTrainer = _trainer;
		}

		_trainer = trainer;
	}

	public String getOriginalTrainer() {
		return GetterUtil.getString(_originalTrainer);
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		_columnBitmask = -1L;

		_date = date;
	}

	@JSON
	@Override
	public Double getHours() {
		return _hours;
	}

	@Override
	public void setHours(Double hours) {
		_hours = hours;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Training.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Training.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Training toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Training>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TrainingImpl trainingImpl = new TrainingImpl();

		trainingImpl.setUuid(getUuid());
		trainingImpl.setTrainingId(getTrainingId());
		trainingImpl.setGroupId(getGroupId());
		trainingImpl.setCompanyId(getCompanyId());
		trainingImpl.setUserId(getUserId());
		trainingImpl.setUserName(getUserName());
		trainingImpl.setCreateDate(getCreateDate());
		trainingImpl.setModifiedDate(getModifiedDate());
		trainingImpl.setTrainer(getTrainer());
		trainingImpl.setName(getName());
		trainingImpl.setDate(getDate());
		trainingImpl.setHours(getHours());

		trainingImpl.resetOriginalValues();

		return trainingImpl;
	}

	@Override
	public int compareTo(Training training) {
		int value = 0;

		value = DateUtil.compareTo(getDate(), training.getDate());

		if (value != 0) {
			return value;
		}

		value = getName().compareTo(training.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Training)) {
			return false;
		}

		Training training = (Training)obj;

		long primaryKey = training.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		TrainingModelImpl trainingModelImpl = this;

		trainingModelImpl._originalUuid = trainingModelImpl._uuid;

		trainingModelImpl._originalGroupId = trainingModelImpl._groupId;

		trainingModelImpl._setOriginalGroupId = false;

		trainingModelImpl._originalCompanyId = trainingModelImpl._companyId;

		trainingModelImpl._setOriginalCompanyId = false;

		trainingModelImpl._setModifiedDate = false;

		trainingModelImpl._originalTrainer = trainingModelImpl._trainer;

		trainingModelImpl._originalName = trainingModelImpl._name;

		trainingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Training> toCacheModel() {
		TrainingCacheModel trainingCacheModel = new TrainingCacheModel();

		trainingCacheModel.uuid = getUuid();

		String uuid = trainingCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			trainingCacheModel.uuid = null;
		}

		trainingCacheModel.trainingId = getTrainingId();

		trainingCacheModel.groupId = getGroupId();

		trainingCacheModel.companyId = getCompanyId();

		trainingCacheModel.userId = getUserId();

		trainingCacheModel.userName = getUserName();

		String userName = trainingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			trainingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			trainingCacheModel.createDate = createDate.getTime();
		}
		else {
			trainingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			trainingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			trainingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		trainingCacheModel.trainer = getTrainer();

		String trainer = trainingCacheModel.trainer;

		if ((trainer != null) && (trainer.length() == 0)) {
			trainingCacheModel.trainer = null;
		}

		trainingCacheModel.name = getName();

		String name = trainingCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			trainingCacheModel.name = null;
		}

		Date date = getDate();

		if (date != null) {
			trainingCacheModel.date = date.getTime();
		}
		else {
			trainingCacheModel.date = Long.MIN_VALUE;
		}

		trainingCacheModel.hours = getHours();

		return trainingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Training, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Training, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Training, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Training)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Training, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Training, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Training, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Training)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Training>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _trainingId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _trainer;
	private String _originalTrainer;
	private String _name;
	private String _originalName;
	private Date _date;
	private Double _hours;
	private long _columnBitmask;
	private Training _escapedModel;

}